WIP view all squids
ohad-porat/consultancy-breakable-toy pull request #1
Opened 2022-02-17 15:24 UTC by ohad-porat

### Accomplished
* Created squids migration, model, and route
* Created SquidList and SquidTile components
* Added `handleErrors` middleware
  * Wrapped routes with `nextWrapper.js`

### Outstanding Items
* Sort squids by creation date
* Create a seeder using fake data
  * I added `rosie`, my plan is to look at the documentation and Kerrin's implementation and then escalate questions as needed
* Make the HTTP requests using the `ApiClient` class
  * Need to read about `axios`
  * Need to read about React Query
* Styling

2022-02-25 20:01 UTC, dpickett requested changes
🚀

2022-02-25 20:01 UTC, dpickett commented on client/src/components/App.jsx
> +  // ohad is a total nerd hahahahahaha ULTIMATE POWERRRRRRRRRR!!!!!!!!!
lol

2022-02-25 20:01 UTC, dpickett commented on client/src/components/squids/SquidList.jsx
> +  const squidTiles = squidListQuery.isLoading
this ternary is a bit hard to read. I might consider instead breaking out components for each state and conditionally returning them. The variable name also gets a little misleading if it represents text that is not related to squids

2022-02-25 20:01 UTC, dpickett commented on client/src/components/squids/SquidTile.jsx
> +      <p>---</p>
you could use a css border to impart this style

2022-02-25 20:01 UTC, dpickett commented on server/src/db/seeders/SquidSeeder.js
> +      await squidFactory.createMany(15)
15 is a lot to create, particularly if. we're seeding in the test suite. It might be a good idea to reduce this count, or make the count conditional on the basis of `NODE_ENV` or another environment variable.

2022-02-25 20:01 UTC, dpickett commented on server/src/routes/api/v1/squidsRouter.js
> +  nextWrapper(async (req, res) => {
nice! I bet you'll tackle this in the pagination story, but it's a good idea to always constrain our index routes. At a minimium, I'll set a provisional limit to a high number like 1000 or 5000 to eliminate the possibility of the server running out of memory with a large record count.

2022-03-07 15:04 UTC, ohad-porat commented on server/src/db/seeders/SquidSeeder.js
> +      await squidFactory.createMany(15)
```javascript
const squidsToCreate = process.env.NODE_ENV === "development" ? 15 : 3
```


```javascript
class Configuration {
  get nodeEnv() {
    return (process.env.NODE_ENV || "") === "" ? "development" : process.env.NODE_ENV
  }
}

const config = new Configuration()
config.nodeEnv
```

2022-03-07 21:29 UTC, ohad-porat commented on server/src/services/Configuration.js
> +}
I noticed that we also have a `getNodeEnv.js` service function in the config folder, should I just use that instead?

2022-03-08 16:55 UTC, dpickett requested changes

2022-03-08 16:55 UTC, dpickett commented on client/src/components/App.jsx
> +import { SquidList } from "./squidIndex/SquidList"
I liked the folder name `squids`

2022-03-08 16:55 UTC, dpickett commented on client/src/components/layout/TopBar.jsx
> +        <li className="menu-text">Da Squids App</li>
it might be good to have this link to the root

2022-03-08 16:55 UTC, dpickett commented on client/src/components/squidIndex/SquidTile.jsx
> +  const hrLineElement = squid.id === "1" ? "" : <hr />
hm - we can't rely on a hard `id` value in production. If we want to separate the tiles I would suggest we do so in the `List` component. 

```javascript
squidListQueryOutput = squids.map((squid) => <div key={squid.id}><SquidTile squid={squid} /><hr /></div>)
```

2022-03-14 18:57 UTC, dpickett requested changes

2022-03-14 18:57 UTC, dpickett commented on client/src/components/squids/SquidList.jsx
> +    <div className="page-body">
since this is specific to squids, I would probably call this `squids-list`

2022-03-14 18:57 UTC, dpickett commented on client/src/components/squids/SquidList.jsx
> +      <h2 className="index-header__text">Squid List</h2>
bem wise, I would call this `squids-list__header`

2022-03-14 18:57 UTC, dpickett commented on client/src/components/squids/SquidTile.jsx
> +    <div className="squid-tile">
consider: `squids-list__tile`

2022-03-14 18:57 UTC, dpickett commented on client/src/components/squids/SquidTile.jsx
> +      <h3 className="squid-tile__header">Name: {squid.name}</h3>
consider `squids-list__tile-header`

2022-03-14 18:57 UTC, dpickett commented on client/src/components/layout/TopBar.jsx
> +          <Link to="/" className="menu-link">
BEM wise, this would probably be: `menu__nav-link`

2022-03-14 19:48 UTC, merged